<a href="https://colab.research.google.com/github/Antoine723/ProjetNLP/blob/main/ProjetNLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [115]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.text import Text
from nltk.stem.lancaster import LancasterStemmer
from nltk.stem import WordNetLemmatizer
import numpy as np
import tensorflow as tf

from gdrive.MyDrive.ProjetNLP.rnn_utils import *

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [238]:
df=pd.read_csv('gdrive/MyDrive/ProjetNLP/training.1600000.processed.noemoticon.csv',encoding="ISO-8859-1",header=None)
data=np.array([df.iloc[0:15][5],df.iloc[800000:800015][5]])

print(data)

[["@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D"
  "is upset that he can't update his Facebook by texting it... and might cry as a result  School today also. Blah!"
  '@Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds'
  'my whole body feels itchy and like its on fire '
  "@nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there. "
  '@Kwesidei not the whole crew ' 'Need a hug '
  "@LOLTrish hey  long time no see! Yes.. Rains a bit ,only a bit  LOL , I'm fine thanks , how's you ?"
  "@Tatiana_K nope they didn't have it " '@twittera que me muera ? '
  "spring break in plain city... it's snowing "
  'I just re-pierced my ears '
  "@caregiving I couldn't bear to watch it.  And I thought the UA loss was embarrassing . . . . ."
  '@octolinz16 It it counts, idk why I did either. you never talk to me anymore '
  "@smarrison i would

# Traitement

In [239]:
def processing(data):

  #MINUSCULES
  for i in range(len(data)):
    for j in range(len(data[i])):
      data[i][j]=data[i][j].lower()

  #TOKENIZATION
  tokenizer = nltk.RegexpTokenizer(r'\w+')

  for i in range(len(data)):
    for j in range(len(data[i])):
      data[i][j]=tokenizer.tokenize(data[i][j])

  #STOPWORDS
  for i in range(len(data)):
    for j in range(len(data[i])):
      data[i][j]=[w for w in data[i][j] if not w in list(nltk.corpus.stopwords.words('english'))]
      

  #STEMMING
  stemmer=LancasterStemmer()
  for i in range(len(data)):
    for j in range(len(data[i])):
      data[i][j]=[stemmer.stem(w) for w in data[i][j]]

  #LEMMATIZATION
  Word_Lemmatizer = WordNetLemmatizer()
  for i in range(len(data)):
    for j in range(len(data[i])):
      data[i][j]=[Word_Lemmatizer.lemmatize(w) for w in data[i][j]]
  print(data)

  return data

In [240]:
data=processing(data)

[[list(['switchfoot', 'http', 'twitp', 'com', '2y1zl', 'awww', 'bum', 'should', 'got', 'david', 'car', 'third', 'day'])
  list(['upset', 'upd', 'facebook', 'text', 'might', 'cry', 'result', 'school', 'today', 'also', 'blah'])
  list(['kenich', 'div', 'many', 'tim', 'bal', 'man', 'sav', '50', 'rest', 'go', 'bound'])
  list(['whol', 'body', 'feel', 'itchy', 'lik', 'fir'])
  list(['nationwideclass', 'behav', 'mad', 'see'])
  list(['kweside', 'whol', 'crew']) list(['nee', 'hug'])
  list(['lolt', 'hey', 'long', 'tim', 'see', 'ye', 'rain', 'bit', 'bit', 'lol', 'fin', 'thank'])
  list(['tatiana_k', 'nop']) list(['twitter', 'que', 'muer'])
  list(['spring', 'break', 'plain', 'city', 'snow'])
  list(['pierc', 'ear'])
  list(['careg', 'bear', 'watch', 'thought', 'ua', 'loss', 'embarrass'])
  list(['octolinz16', 'count', 'idk', 'eith', 'nev', 'talk', 'anym'])
  list(['smarrison', 'would', 'first', 'gun', 'real', 'though', 'zac', 'snyd', 'doucheclown'])]
 [list(['lov', 'health4uandpets', 'u', 'guy

In [241]:
from collections import defaultdict
v=set()
for i in range(len(data)):
  for j in range(len(data[i])):
    for h in range(len(data[i][j])):
      v.add(data[i][j][h])

vocab = defaultdict(lambda: 0)
vocab['<PAD>'] = 1

j=2
for i in v:
  vocab[i]=j
  j+=1
print(vocab)

defaultdict(<function <lambda> at 0x7f365d0cf1e0>, {'<PAD>': 1, 'snow': 2, 'smarrison': 3, 'que': 4, 'break': 5, 'ua': 6, 'are': 7, 'dm': 8, 'addict': 9, 'bear': 10, 'bless': 11, 'embarrass': 12, 'answ': 13, 'friend': 14, 'lost': 15, 'long': 16, 'bet': 17, 'anym': 18, 'careg': 19, 'pierc': 20, 'hah': 21, 'blah': 22, 'go': 23, 'also': 24, 'hang': 25, 'hour': 26, 'two': 27, 'lovesbrooklyn2': 28, 'sweetheart': 29, 'tonight': 30, 'forget': 31, 'mr': 32, 'com': 33, 'talk': 34, 'would': 35, 'stupid': 36, 'see': 37, 'im': 38, 'sulk': 39, 'on': 40, 'keepinupwkr': 41, 'fir': 42, 'birthday': 43, 'nationwideclass': 44, 'nileyjileyluv': 45, 'city': 46, 'food': 47, 'soup': 48, 'rest': 49, 'find': 50, 'lol': 51, 'rain': 52, 'tim': 53, 'hurt': 54, 'zac': 55, 'show': 56, 'lik': 57, 'gun': 58, 'man': 59, 'effect': 60, 'lt': 61, 'join': 62, 'ear': 63, 'congr': 64, 'thank': 65, 'respons': 66, 'watch': 67, 'result': 68, 'snyd': 69, 'ad': 70, 'kenich': 71, 'behav': 72, 'ye': 73, 'loss': 74, 'r': 75, 'gre':

In [242]:
def transformWords(data):
  matrixData=[]
  maxLen=0
  for i in range(len(data)):
    for j in range(len(data[i])):
      if (maxLen < len(data[i][j])):
        maxLen= len(data[i][j])

  for i in range(len(data)):
    for j in range(len(data[i])):
      test=[]
      for k in range(maxLen):
        if (k >= len(data[i][j])):
          test.append(vocab['<PAD>'])
        else:
          test.append(vocab[data[i][j][k]])
      matrixData.append(test)
  return matrixData

In [243]:
data=transformWords(data)
datas=np.array([df.iloc[5:10][5],df.iloc[800005:800010][5]])
datas=processing(datas)
datas=transformWords(datas)

[[list(['kweside', 'whol', 'crew']) list(['nee', 'hug'])
  list(['lolt', 'hey', 'long', 'tim', 'see', 'ye', 'rain', 'bit', 'bit', 'lol', 'fin', 'thank'])
  list(['tatiana_k', 'nop']) list(['twitter', 'que', 'muer'])]
 [list(['productoffear', 'tel', 'burst', 'laugh', 'real', 'loud', 'thank', 'mak', 'com', 'sulk'])
  list(['r_keith_hill', 'than', 'respons', 'ihad', 'already', 'find', 'answ'])
  list(['keepinupwkr', 'jeal', 'hop', 'gre', 'tim', 'vega', 'lik', 'acm', 'lov', 'show'])
  list(['tommcf', 'ah', 'congr', 'mr', 'fletch', 'fin', 'join', 'twit'])
  list(['e4voip', 'respond', 'stupid', 'cat', 'help', 'typ', 'forg', 'er'])]]


In [244]:
data=np.array(data)

In [231]:
def buildModel():
  model=tf.keras.Sequential()
  model.add(tf.keras.layers.Embedding(input_dim=len(vocab)+1,output_dim=1))
  model.add(tf.keras.layers.LSTM(128,activation="relu"))
  model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
  return model

In [245]:
print(data)

[[ 85 180 114  33  88 102 109 110 144 162 151 156 103   1   1   1]
 [174  78 153 129  79 141  68  93 147  24  22   1   1   1   1   1]
 [ 71 182  97  53 157  59 161 204  49  23 173   1   1   1   1   1]
 [191  87  98 116  57  42   1   1   1   1   1   1   1   1   1   1]
 [ 44  72  92  37   1   1   1   1   1   1   1   1   1   1   1   1]
 [131 191 135   1   1   1   1   1   1   1   1   1   1   1   1   1]
 [163 198   1   1   1   1   1   1   1   1   1   1   1   1   1   1]
 [107 123  16  53  37  73  52 164 164  51 115  65   1   1   1   1]
 [127 201   1   1   1   1   1   1   1   1   1   1   1   1   1   1]
 [203   4 113   1   1   1   1   1   1   1   1   1   1   1   1   1]
 [106   5 195  46   2   1   1   1   1   1   1   1   1   1   1   1]
 [ 20  63   1   1   1   1   1   1   1   1   1   1   1   1   1   1]
 [ 19  10  67 150   6  74  12   1   1   1   1   1   1   1   1   1]
 [ 90 139 165 199 192  34  18   1   1   1   1   1   1   1   1   1]
 [  3  35  89  58 148 101  55  69 146   1   1   1   1   1   1 

In [128]:
# print(y_train)

In [248]:
model=buildModel()
# def fitModel(model,trainSize): #trainSize = taille des données prises en compte pour le fit (ex : si on crée le modèle en lui donnant 20 phrases, trainSize=20)
#Attention, ici on a configuré le y_train pour qu'il y ait une part égale de commentaires positifs/négatifs
y_train=np.concatenate([np.zeros((15,1)),np.ones((15,1))])
model.compile(loss='binary_crossentropy',optimizer="adam")
model.fit(data,y_train,epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 0.6931
Epoch 2/50
1/1 [==============================] - 0s 22ms/step - loss: 0.6929
Epoch 3/50
1/1 [==============================] - 0s 17ms/step - loss: 0.6927
Epoch 4/50
1/1 [==============================] - 0s 21ms/step - loss: 0.6926
Epoch 5/50
1/1 [==============================] - 0s 21ms/step - loss: 0.6925
Epoch 6/50
1/1 [==============================] - 0s 21ms/step - loss: 0.6923
Epoch 7/50
1/1 [==============================] - 0s 20ms/step - loss: 0.6920
Epoch 8/50
1/1 [==============================] - 0s 19ms/step - loss: 0.6918
Epoch 9/50
1/1 [==============================] - 0s 18ms/step - loss: 0.6914
Epoch 10/50
1/1 [==============================] - 0s 21ms/step - loss: 0.6909
Epoch 11/50
1/1 [==============================] - 0s 22ms/step - loss: 0.6903
Epoch 12/50
1/1 [==============================] - 0s 23ms/step - loss: 0.6895
Epoch 13/50
1/1 [==============================] - 0s 23ms/step

In [251]:
model.predict(datas)

array([[1.10714380e-08],
       [2.34102657e-08],
       [1.05887485e-08],
       [1.29744659e-09],
       [3.56525183e-04],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00]], dtype=float32)

In [195]:
print(data[0].shape)

(16,)


In [196]:
print(len(df))

1600000
